[[redirects]]
  from = "/api/*"
  to = "https://netease-cloud-music-api-mu-self.vercel.app/:splat"
  status = 200
  force = true
  [redirects.headers]
    X-From = "Netlify"
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200